---
title: "Day 22 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
options(scipen = 999)
```

```{r}
input<-read_lines("Day22Sample.txt")
bl<-which(input=="")
P1<-as.numeric(input[2:(bl-1)])
P2<-as.numeric(input[(bl+2):length(input)])

```

## Part 1

Play war
```{r}
playwar<-function(p1,p2){
  while(length(p1)>0&&length(p2)>0){
    a<-p1[1]
    b<-p2[1]
    p1<-p1[-1]
    p2<-p2[-1]
    if(a>b){p1<-c(p1,a,b)}else{p2<-c(p2,b,a)}}
  
if(length(p1)==0){p2}else{p1}}
```

```{r}
winningcards<-playwar(P1,P2)
score<-sum(winningcards*(length(winningcards):1))
score
```

## Part 2

More rules

```{r}
recursivecombat<-function(p1,p2){
  hands<-dict()
  gameround<-1
  while(T){
# if either of the hands is empty, stop and declare a winner
    if(length(p1)==0){
      winner<-"P2"
      break}
    if(length(p2)==0){
      winner<-"P1"
      break}
    ## if been there before, P1 is winner - then mark hands that have happened
    if(hands$has(c(1001,p1))|hands$has(c(2002,p2))){
      winner<-"P1"
      break}
    hands$set(c(1001,p1),p1)
    hands$set(c(2002,p2),p2)
    ## get top two cards and update the hands
    card1<-p1[1]
    card2<-p2[1]
    p1<-p1[-1]
    p2<-p2[-1]
    ## pick the "winner" either by playing the subgame if the hands are long enough
    ## and the cards are high enough, or just high card wins
    if(length(p1)>=card1&&length(p2)>=card2){
      winner<-recursivecombat(p1[1:card1],p2[1:card2])[[1]]
    }else if(card1>card2){
      winner<-"P1"
    }else{winner<-"P2"}
    ## depending on which the winner is move the cards around
    if(winner=="P1"){
      p1<-c(p1,card1,card2)
      p2<-p2
    }else{
        p2<-c(p2,card2,card1)
        p1<-p1}
    gameround<-gameround+1}
return(list(winner,p1,p2))}
```

Create a wrapper

```{r}
playrecursivecombat<-function(p1,p2){
  w<-recursivecombat(p1,p2)
  if(w[[1]]=="P1"){w<-w[[2]]}else{w<-w[[3]]}
  cat(w,"\n")
  w<-w*(length(w):1)
  w<-sum(w)
w}
```

```{r}
playrecursivecombat(P1,P2)
# 33647
```

