---
title: "Day 2 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
options(scipen = 999)
```

```{r}
input<-read_lines("Day2Sample.txt")
```

## Part 1
```{r}
part1<-sapply(input,function(x){
  ## split the string into pieces
  x<-str_split(x,"-| |: ")
  ## count the repeats
  y<-str_count(x[[1]][4],x[[1]][3])
  ## check to see if between the upper and lower bounds
  if(y>=as.numeric(x[[1]][1])&&y<=as.numeric(x[[1]][2])){p1<-1}else{p1<-0}
  p1})
part1<-sum(part1)
part1
```
## Part 2
```{r}
part2<-sapply(input,function(x){
  ## split the string into pieces
  x<-str_split(x,"-| |: ")
  ## count the repeats
  y<-str_sub(x[[1]][4],as.numeric(x[[1]][1]),as.numeric(x[[1]][1]))
  z<-str_sub(x[[1]][4],as.numeric(x[[1]][2]),as.numeric(x[[1]][2]))
  ## check to see if between the upper and lower bounds
  if(xor(x[[1]][3]==y,x[[1]][3]==z)){p2<-1}else{p2<-0}
  p2})
part2<-sum(part2)
part2
```
